=== Victoria-Sampalo/XML/SCHEMA/EjercicioPersona/Persona.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="personas" type="tipoPersonas"/>

<xs:complexType name="tipoPersonas">
    <xs:sequence>
        <xs:element name="persona" type="tipoPersona"
        maxOccurs="unbounded"/>
    </xs:sequence>


</xs:complexType>

<xs:complexType name="tipoPersona">
    <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="direccion" type="tipoDireccion" 
        maxOccurs="unbounded"/>
    </xs:sequence>

</xs:complexType>


<xs:complexType name="tipoDireccion">
    <xs:sequence>
        <xs:element name="calle" type="xs:string"/>
        <xs:element name="poblacion" type="xs:string"/>
        <xs:element name="provincia" type="xs:string"/>
        <xs:element name="cpostal" type="xs:string"/>
    </xs:sequence>

</xs:complexType>



</xs:schema>

=== Victoria-Sampalo/XML/SCHEMA/EjercicioPersona/Persona.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Persona.xsd">

    <personas>
        <persona>
            <nombre>Juan Pardo</nombre>
            <nacimiento dia="10" mes="Abril" anyo="1982"></nacimiento>
            
            <direccion>
                <calle>Caoba,1</calle>
                <poblacion>Madrid</poblacion>
                <provincia>Madrid</provincia>
                <cpostal>28005</cpostal>

            </direccion>
            
        </persona>

        <persona>
            <nombre>María López</nombre>
           
             <direccion>
                <calle>Roncato,1</calle>
                <poblacion>Illescas</poblacion>
                <provincia>Toledo</provincia>
                <cpostal>45200</cpostal>

            </direccion>
            <direccion>
                <calle>Paseo de la Esperanza 15, 1º A</calle>
                <poblacion>Madrid</poblacion>
                <provincia>Madrid</provincia>
                <cpostal>28005</cpostal>

            </direccion>
       
        </persona>



    </personas>
