<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE biblioteca [
<!ELEMENT biblioteca (libros,autores,editoriales)>
<!ELEMENT libros (libro)+>
<!ELEMENT libro (titulo,fechapubli,precio,distribuidor,revision?)>
<!ATTLIST libro isbn ID #REQUIRED autores IDREFS #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT fechapubli (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT distribuidor EMPTY>
<!ATTLIST distribuidor id IDREF #REQUIRED>
<!ATTLIST precio moneda CDATA #REQUIRED>
<!ELEMENT revision EMPTY>
<!ATTLIST revision revisor IDREFS #REQUIRED valoracion CDATA #REQUIRED comentario CDATA #IMPLIED>

<!ELEMENT autores (autor)+>
<!ELEMENT autor (nombre,apellidos,email?)>
<!ATTLIST autor nif ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT editoriales (editorial)+>
<!ELEMENT editorial (oficina,web)>
<!ATTLIST editorial nombre ID #REQUIRED>
<!ELEMENT oficina (#PCDATA)>
<!ELEMENT web (#PCDATA)>
]>

<biblioteca>
 <libros>
  <libro isbn="_1-55655-767-6" autores="_23456788P _23456787G">
   <titulo>Fundamentos de bases de datos</titulo>
   <fechapubli>2003</fechapubli>
   <precio moneda="euro">40</precio>
   <distribuidor id="_McGraw-Hill" />
   <revision revisor="_23456789N" valoracion="8.5" comentario="Es un libro de texto básico" />
  </libro>
  
  <libro isbn="_5-48963-568-7" autores="_23456788P _80604128M">
   <titulo>Fundamentos de programación</titulo>
   <fechapubli>2022</fechapubli>
   <precio moneda="euro">80</precio>
   <distribuidor id="_Planeta" />
  </libro>
  
  <libro isbn="_8-54678-212-6" autores="_56974132E">
   <titulo>Ciencias en el medio ambiente</titulo>
   <fechapubli>2012</fechapubli>
   <precio moneda="euro">60</precio>
   <distribuidor id="_Vicens-Vives" />
   <revision revisor="_23456788P _80604128M _23456787G" valoracion="4.5" comentario="No está correctamente documentado" />
  </libro>
 </libros>
 
 <autores>
  <autor nif="_23456788P">
   <nombre>Abraham</nombre>
   <apellidos>Silberschatz</apellidos>
   <email>silbers@hotmail.com</email>
  </autor>
  
  <autor nif="_23456787G">
   <nombre>Henry</nombre>
   <apellidos>Korth</apellidos>
   <email>korth@hotmail.com</email>
  </autor>
  
  <autor nif="_23456789N">
   <nombre>James</nombre>
   <apellidos>Smith</apellidos>
  </autor>
  
   <autor nif="_80604128M">
   <nombre>Antonio</nombre>
   <apellidos>Martin</apellidos>
  </autor>
  
   <autor nif="_56974132E">
   <nombre>Joaquin</nombre>
   <apellidos>Karl</apellidos>
   <email>karl.joaquin20@hotmail.com</email>
  </autor>
 </autores>
 
 <editoriales>
  <editorial nombre="_McGraw-Hill">
   <oficina>Av. Santander s/n</oficina>
   <web>http://www.mcgrawhill.es</web>
  </editorial>
  
  <editorial nombre="_Planeta">
   <oficina>Av. Santander 10</oficina>
   <web>http://www.editorialplaneta.es</web>
  </editorial>
  
  <editorial nombre="_Vicens-Vives">
   <oficina>Calle San Miguel 9</oficina>
   <web>http://www.vicensvives.es</web>
  </editorial>
 </editoriales>
</biblioteca>