<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca [

<!ELEMENT biblioteca (libros,autores,editoriales)>
<!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo,precio,fec_publica,revisiones?)>
<!ELEMENT titulo (#PCDATA)>
<!ATTLIST libro isbn ID #REQUIRED
		autores IDREFS #REQUIRED
		editorial IDREF #REQUIRED
		>		

<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda (euro) #REQUIRED>

<!ELEMENT fec_publica (#PCDATA)>
<!ELEMENT revisiones (revision+)>
<!ELEMENT revision (valoracion, comentario?)>
<!ATTLIST revision autor IDREF #REQUIRED>
<!ELEMENT valoracion (#PCDATA)>
<!ELEMENT comentario (#PCDATA)>


<!ELEMENT autores (autor+)>
<!ELEMENT autor (nombre,apellidos,email?)>
<!ATTLIST autor nif ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT email (#PCDATA)>



<!ELEMENT editoriales (editorial+)>
<!ELEMENT editorial (oficina,web)>

<!ATTLIST editorial nombre ID #REQUIRED>
<!ELEMENT oficina (#PCDATA)>
<!ELEMENT web (#PCDATA)>

]>

<biblioteca>
	<libros>
	  
	  <libro isbn="_1-55655-767-6"
	  	autores="_23456788P _23456787G"
	  	editorial="McGraw-Hill">
	  	<titulo>Fundamentos de bases de datos</titulo>
	  	<precio moneda="euro">40</precio>
	  	<fec_publica>2003</fec_publica>
	  	<revisiones>
	  	 <revision autor="_23456789N">
	  	    <valoracion>8.5</valoracion>
	  	    <comentario>Es un libro de texto básico</comentario>
	  	 </revision>
	  </revisiones>
	  	
	  
	  </libro>
	<!--con dos autores y sin revision-->
	 <libro isbn="_1-55655-767-7"
	  	autores="_23456788P _79055930H"
	  	editorial="Planeta">
	  	<titulo>Fundamentos de VicoPiko</titulo>
	  	<precio moneda="euro">45</precio>
	  	<fec_publica>2004</fec_publica>
	  	
	  	
	  
	  </libro>
	<!--con 1 autor y tres revisores-->
	  <libro isbn="_1-55655-767-8"
	  	autores="_23456789N"
	  	editorial="Planeta">
	  	<titulo>Fundamentos de XML</titulo>
	  	<precio moneda="euro">20</precio>
	  	<fec_publica>2003</fec_publica>
	  	<revisiones>
	  	 <revision autor="_23456788P">
	  	    <valoracion>5.4</valoracion>
	  	 </revision>
	  	 <revision autor="_23456787G">
	  	    <valoracion>5</valoracion>
	  	    <comentario>Muy básico</comentario>
		</revision>
	  	 
	  	 <revision autor="_79055930H">
	  	    <valoracion>4</valoracion>
	  	    </revision>
	  	 </revisiones>
	  	
	  
	  </libro>
	  
	</libros>
	
	<autores>
	 <autor nif="_23456788P">
	  	<nombre>Abraham</nombre>
	  	<apellidos>Silberschatz</apellidos>
	  	<email>silbers@hotmail.com</email>
	  </autor>
	   <autor nif="_23456787G">
	  	<nombre>Henry</nombre>
	  	<apellidos>Korth</apellidos>
	  	<email>korth@hotmail.com</email>
	  </autor>
	  <autor nif="_23456789N">
	  	<nombre>James</nombre>
	  	<apellidos>Smith</apellidos>
	  	
	  </autor>
	  <autor nif="_79055930H">
	  	<nombre>Victoria</nombre>
	  	<apellidos>Sampalo</apellidos>
	  	<email>sampalo@hotmail.com</email>
	  </autor>

	</autores>
	
	<editoriales>
		<editorial nombre="McGraw-Hill">
			<oficina>Av. Santander s/n</oficina>
	  		<web>http://www.mcgrawhill.es</web>
		</editorial>
		<editorial nombre="Planeta">
	  		<oficina>Av. Santander s/n</oficina>
	  		<web>http://www.planeta.es</web>
	  	</editorial>

	</editoriales>
	 
	  
	  

</biblioteca>
