<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca[
<!ELEMENT biblioteca (libros,autores,editoriales)>

<!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo,precio,fechapubli, revisiones)>

<!ELEMENT titulo (#PCDATA)>
<!ATTLIST libro isbn ID #REQUIRED
                autores IDREFS #REQUIRED
                editorial IDREF #REQUIRED 
                 >

<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda (euro) #REQUIRED>
<!ELEMENT fechapubli (#PCDATA)>

<!ELEMENT revisiones (revision+)>
<!ELEMENT revision (valoracion, comentario?)>

<!ATTLIST revision autor IDREF #REQUIRED >
<!ELEMENT valoracion (#PCDATA)>
<!ELEMENT comentario (#PCDATA)>

<!ELEMENT  autores (autor+)>
<!ELEMENT autor (nombre, apellidos, email?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST autor nif ID #REQUIRED > 
<!--ES ID Y EN LOS OTROS IDREF DONDE SE REFIERE -->


<!ELEMENT editoriales (editorial+)>
<!ELEMENT editorial (oficina, web)>
<!ELEMENT oficina (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ATTLIST editorial nombre ID #REQUIRED>
]>

<biblioteca>
    <libros>
        <libro isbn="_1-55655-767-6"
            autores="_23456788P _23456787G"
            editorial="McGraw-Hill">
        <titulo>Fundamentos de bases de datos</titulo>
       <precio moneda="euro">40</precio>
       <fechapubli>2003</fechapubli>
        <revisiones>
            <revision autor="_23456789N">
                <valoracion>8.5</valoracion>
                <comentario>“Es un libro de texto básico”</comentario>
            </revision>
        </revisiones>
    
        </libro>
    </libros>
    <autores>
        <autor nif="_23456788P">
            <nombre>Abraham  </nombre>
            <apellidos>Silberschatz</apellidos>
            <email>silbers@hotmail.com</email>
        </autor>
        <autor nif="_23456787G">
            <nombre>Henry</nombre>
            <apellidos>Korth</apellidos>
            <email>korth@hotmail.com</email>
        </autor>
        <autor nif="_23456789N">
            <nombre>James</nombre>
            <apellidos>Smith</apellidos>
            
        </autor>
    </autores>
    <editoriales>
		<editorial nombre="McGraw-Hill">
			<oficina>Av. Santander s/n</oficina>
	  		<web>http://www.mcgrawhill.es</web>
		</editorial>
		<editorial nombre="Planeta">
	  		<oficina>Av. Santander s/n</oficina>
	  		<web>http://www.planeta.es</web>
	  	</editorial>

	</editoriales>
    
</biblioteca>
